allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}
subprojects {
    plugins.withId("org.jetbrains.kotlin.android") {
        tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
            compilerOptions.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)
        }
    }
    def forceLibraryCompileSdk = {
        if (project.plugins.hasPlugin("com.android.library")) {
            project.android.compileSdkVersion 36
        }
    }
    if (project.state.executed) {
        forceLibraryCompileSdk()
    } else {
        project.afterEvaluate {
            forceLibraryCompileSdk()
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
